# Generated by Django 4.2.3 on 2023-07-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("director", "director"),
                    ("candidate", "candidate"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
